spring.application.name=prod-ready-features

spring.jpa.hibernate.ddl-auto=create 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:mysql://localhost:3307/prod_ready_features
spring.datasource.username=root
spring.datasource.password=Sujit@123

#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql


spring.devtools.restart.enabled=true
spring.devtools.restart.exclude=com/codingshuttle/anuj/prod_ready_features/prod_ready_features/dto/PostDTO.java/**
#Excluding DTO only stops restart, not class update.
spring.devtools.restart.pollInterval = 20
spring.devtools.restart.quietPeriod=10

#spring.devtools.remote=true
